In [45]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

1.Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [46]:
a = np.arange(12,24,1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [47]:
m1 = np.reshape(a, (2,6))
m2 = np.reshape(a, (3,4))
m3 = np.reshape(a, (4,3))
m4 = np.reshape(a, (6,2))
m5 = np.reshape(a, (1,12))


3.Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [48]:
m1 = np.reshape(a, (-1,2))
m2 = np.reshape(a, (-1,3))
m3 = np.reshape(a, (2,-1))
m4 = np.reshape(a, (4,-1))
m5 = np.reshape(a, (6,-1))


3.Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Ответ: Такой массив является одномерным

5.Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [49]:
ar1 = np.random.randn(3,4)
ar2 = np.reshape(ar1, (1,12))

6.Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
                    состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2

In [50]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [51]:
b = np.reshape(np.arange(20,1,-2),(1,10))
print(a)
print(b)

[20 18 16 14 12 10  8  6  4  2]
[[20 18 16 14 12 10  8  6  4  2]]


8.Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10

In [52]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
С = np.vstack((a, b))
print(c)
c.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

9.Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [53]:
a = np.arange(0,12,1)
a = np.reshape(a,(4,3))
At = a.T
B = a.dot(At)
print('Размер матрицы B',B.shape)
print('Определитель матрицы B',np.linalg.det(B))
B

Размер матрицы B (4, 4)
Определитель матрицы B 0.0


array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Ответ: Поскольку определитель матрицы равен нулю, то обратную матрицу посчитать можно.

 10.Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [54]:
import random
random.seed(42)
print(random.random())

0.6394267984578837


11.Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно

In [55]:
C = np.random.randint(0,16,16)
C 

array([ 1,  7,  5, 14,  1,  9, 11, 12,  5,  4,  6,  6,  3,  5, 11, 14])

12.Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [56]:
C = np.reshape(C,(4,4))
D = C * 10 + B
D_inv = np.linalg.inv(D)
print('Определитель матрицы равен: ', np.linalg.det(D) )
print('Ранг матрицы равен: ', np.linalg.matrix_rank(D) )

Определитель матрицы равен:  47141199.99999992
Ранг матрицы равен:  4


13.Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C

In [57]:
D_inv[D_inv>0] = 1
D_inv[D_inv<0] = 0
D_inv

array([[1., 0., 1., 0.],
       [1., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.]])

In [58]:
E = np.where(D_inv, B, C)
E

array([[  5,   7,  23,  14],
       [ 14,  50,  86,  12],
       [  5,  86,   6, 212],
       [ 32,   5,  11, 302]])